language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "merck"
    token:
      secure: "JbWEVfh1h0gQ3rkTenxjjVd7KkIrmtBrtpRCfiFH9juTLbRSDmmGZ6G8YN+3OPCyfml2+JWmkNCM0glB9uvcW3bRKoHajlRs//ineF078+fUEa0x1kL5GQB0pG2P3qcUu+frbuyJSakzSEGMFWl3idWgJU6zUjxIk9wc/hFZ0K0Rt7SlTnalx6N0/JmqWHJfX+ZBq1XUnwjNZ3LKp491A8nzqLIDjepNUXJWdjPFg8SgfiFQXvqDrfzm320GlMtGUFa1gIb7A1Atb/gJDRyIhFsEk3YEW9dQM9ujhmMj2PJEp6TaFBNaEE8NUE/n8BvXNRf5PABHpN2NZc3Zt4O7Qndkg5R2wZKbswnoCMBpbDb4elS4YNlIZciYgQtFizfYQn9XqZGpXDkcfOP+/6pSrp6hMfWomv6LJP6X8zly7ZiBBJI3tWvlCkcoqaqvOygmU0Uuu5aFU4ZMkNTv6f9O3aBJ9XNUkXoBRZ1t5JJYcAlGtgAoaVKzY/zFHkxuvKwRYbesPaPc1FIOKYs8Q6dFLih4/zq0Ra53bNWAmQ0iDOk6gODYBt6Q8zhYbHSAl1OlDa/cB/NOE2Or6gdW1r5tQnv7ZuD9YssNWxGSgsiKk9c5dwg6wyfaI0igbddotLq3OpF/e04A+HGYqK4CfeVeuQVKtKJsGEn7MJ0nxM1t4p0="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
before_deploy:
- "./mvnw help:evaluate -N -Dexpression=project.version|grep -v '\\['"
- export project_version=$(./mvnw help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  name: "$project_version"
  api_key:
    secure: onfsrL37o8RTd40kgsc6vciz4Ong9kIkZz9d2Y8AWKDAOf1qj/lZ8xslbKXuoGzuOYc3Wy7pCWZ7JymJNIWyWLMz6xjVEFH2q0VUn0ToCApUoORdYe2+y7ZrmXPJgRUmciDYskeprJySElthOzt1/I3lJ9DopTxW5B/DbxEsLnRHtasmilmdWT5c+X7IKba4X87Q+nC7FJcLn8H6q+YYYi5u9HNqAfNYGOB2Hj3eYaCze/Dge6HJDOmjzpPrPE9Cp1BAl+VVAPRp7ctaMIu1ImEjd8CC6L49CLrxTGl/7Vi49bg9ukdp67Uw1MbyOoxHNLdowmhXalZCtj2vJ352+7Cc3206/1Ssi0I3Ok09EV/wGLDDgxvagg3EvFko10oXHchyxurFS1W5cTQ5eM+/YPi22A/1IZwfIKLOV4A9gowFMaf9gZmd4Kfxh1/+36SmbdR2lB2tCJ3681wI/tli0YvFmLFTN8f+8rpWonu/e5DPfTkgKUXjqY2bZg80h9LvmXb9wrDZZip6WDQK3WDuTvCjl2KVhD71eic/ze+bzbIfdwuhY4T1N0u0XNgmfXSAJIaMSJsPiLE5o3A2GPY1Pi9ljvkbHL0NPOWBNlaBuuhQIROogBT2hRdo1S72XU60/FRf8RXLrkuMMuVe+cXwOqi3CSJRh0uUMtIPVyzjQmY=
  skip_cleanup: true
  file:
  - target/sonar-r-plugin-$project_version.jar
  on:
    tags: true
