language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "merck"
    token:
      secure: "JbWEVfh1h0gQ3rkTenxjjVd7KkIrmtBrtpRCfiFH9juTLbRSDmmGZ6G8YN+3OPCyfml2+JWmkNCM0glB9uvcW3bRKoHajlRs//ineF078+fUEa0x1kL5GQB0pG2P3qcUu+frbuyJSakzSEGMFWl3idWgJU6zUjxIk9wc/hFZ0K0Rt7SlTnalx6N0/JmqWHJfX+ZBq1XUnwjNZ3LKp491A8nzqLIDjepNUXJWdjPFg8SgfiFQXvqDrfzm320GlMtGUFa1gIb7A1Atb/gJDRyIhFsEk3YEW9dQM9ujhmMj2PJEp6TaFBNaEE8NUE/n8BvXNRf5PABHpN2NZc3Zt4O7Qndkg5R2wZKbswnoCMBpbDb4elS4YNlIZciYgQtFizfYQn9XqZGpXDkcfOP+/6pSrp6hMfWomv6LJP6X8zly7ZiBBJI3tWvlCkcoqaqvOygmU0Uuu5aFU4ZMkNTv6f9O3aBJ9XNUkXoBRZ1t5JJYcAlGtgAoaVKzY/zFHkxuvKwRYbesPaPc1FIOKYs8Q6dFLih4/zq0Ra53bNWAmQ0iDOk6gODYBt6Q8zhYbHSAl1OlDa/cB/NOE2Or6gdW1r5tQnv7ZuD9YssNWxGSgsiKk9c5dwg6wyfaI0igbddotLq3OpF/e04A+HGYqK4CfeVeuQVKtKJsGEn7MJ0nxM1t4p0="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
before_deploy:
- "./mvnw help:evaluate -N -Dexpression=project.version|grep -v '\\['"
- export project_version=$(./mvnw help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  name: "$project_version"
  api_key:
    secure: "EP0hBM5DWQtJNR7BJ6e5ZXwu/49bHYqC+TutIo6HcSC60+XTegBPWpcwYm+PJEU+36GsSLYE/AY1GCPwKmcAQdeBW9FhpidvyoSUX0I+bVx2iRbMVmDjHwVhzpGLtIPNIDAEmgbtLeXDhWjOwd6L/Hzo8v2AOAa/RKcATM5oJ+ApccBVJ/ih/HPZe/D55PbmvHac3Xrh8AVPmR6k5AVUOF9+Z/gajwaYXETRdfCGgQ6O+5apirW/WKDnKZj7K18706Xyr4VXmnivx3+LyVCKkmat6y/ziFp01cgviiEH7PJURw6q/Hb/CNj2aeYR0tHCNcuOr10NpQ0QxExsGfZRqP5u3NvmLAoUz1Ks/EO2no+2m8+w4LDZAA38TkOCviwSIsgnILPWEblZjkQrUQwvLrTl/mb39gHLIOrFyhyMOL3Uv5Wo80cOjP2hXGkB84MMWCYQ3JRObcu8OHAum8nkhQE8Bfo8+Bn5RJrp4JuZ/3CJL6gnhB8p8VSHkFeaszzAfGL8KEVFI7pYX44HZJZHkSvu3uMsOeGjLoRFitKYfkywH5R3rB8rFz6f3Y2N9SXjPXMtHz4hV8h6RILugwk0p49dTrrMVm4Cg0bHJ7LDng8pSQ4DQ2dbVkmQ/3g3Q0dm0A5ofCDh26x8QdhIE9uaQzHesZ5An4OT8T/c6lcA5ak="
  skip_cleanup: true
  file:
  - target/sonar-r-plugin-$project_version.jar
  on:
    tags: true
