name: Maven Package
on:
  push:
    branches-ignore: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Package with Maven
        run: ./mvnw --batch-mode package
